import { jsPDF } from "jspdf";

// Type definition for proof packet - accepts both service response and API response formats
interface ProofPacket {
    id: string;
    workspaceId: string;
    taskId?: string | null;
    status?: string | null;
    aiSummary?: string | null;
    aiSummaryModel?: string | null;
    hashChainRoot?: string | null;
    exportedUrl?: string | null;
    closedAt?: string | Date | null;
    createdAt: string | Date;
    updatedAt?: string | Date;
}

interface PDFGeneratorOptions {
    proof: ProofPacket;
    events?: Array<{
        id: string;
        eventType: string;
        payload?: Record<string, unknown>;
        createdAt: string;
        eventHash?: string | null;
    }>;
    workspaceName?: string;
    brandColor?: string;
}

/**
 * Generates a branded PDF for a Proof Packet
 * Contains: Header, AI Summary, Event Timeline, Hash Verification
 */
export async function generateProofPDF(options: PDFGeneratorOptions): Promise<Buffer> {
    const { proof, events = [], workspaceName = "ShipDocket" } = options;

    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // ============================================
    // Header
    // ============================================
    doc.setFillColor(15, 23, 42); // Dark background
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Proof Packet", margin, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by ${workspaceName}`, margin, 33);

    doc.setFontSize(10);
    doc.text(proof.taskId || "N/A", pageWidth - margin, 25, { align: "right" });
    doc.text(new Date().toLocaleDateString(), pageWidth - margin, 33, { align: "right" });

    yPos = 55;

    // ============================================
    // Status Badge
    // ============================================
    doc.setTextColor(0, 0, 0);
    const statusColors: Record<string, [number, number, number]> = {
        draft: [234, 179, 8],
        pending: [249, 115, 22],
        finalized: [34, 197, 94],
        exported: [59, 130, 246],
    };
    const proofStatus = proof.status || "draft";
    const statusColor = statusColors[proofStatus] || [107, 114, 128];

    doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.roundedRect(margin, yPos, 30, 8, 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(proofStatus.toUpperCase(), margin + 15, yPos + 5.5, { align: "center" });

    yPos += 20;

    // ============================================
    // Task Details
    // ============================================
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Task Details", margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(75, 85, 99);

    const details = [
        ["Task ID", proof.taskId || "N/A"],
        ["Created", new Date(proof.createdAt).toLocaleString()],
        ["Status", proof.status || "N/A"],
    ];

    if (proof.closedAt) {
        details.push(["Closed", new Date(proof.closedAt).toLocaleString()]);
    }

    for (const [label, value] of details) {
        doc.setTextColor(107, 114, 128);
        doc.text(`${label}:`, margin, yPos);
        doc.setTextColor(0, 0, 0);
        doc.text(String(value), margin + 30, yPos);
        yPos += 6;
    }

    yPos += 10;

    // ============================================
    // AI Summary
    // ============================================
    if (proof.aiSummary) {
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("AI Summary", margin, yPos);
        yPos += 8;

        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, yPos, pageWidth - margin * 2, 40, 3, 3, "F");

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);

        const summaryLines = doc.splitTextToSize(proof.aiSummary, pageWidth - margin * 2 - 10);
        doc.text(summaryLines, margin + 5, yPos + 8);

        yPos += 50;

        if (proof.aiSummaryModel) {
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text(`Generated by ${proof.aiSummaryModel}`, pageWidth - margin, yPos - 5, {
                align: "right",
            });
        }
    }

    // ============================================
    // Event Timeline
    // ============================================
    if (events.length > 0) {
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Event Timeline", margin, yPos);
        yPos += 10;

        const eventIcons: Record<string, string> = {
            handshake: "🤝",
            pr_opened: "📂",
            pr_merged: "✅",
            pr_approved: "👍",
            ci_passed: "🟢",
            ci_failed: "🔴",
            closure_proposed: "📋",
            closure_approved: "✅",
            jira_status_changed: "📝",
        };

        for (const event of events.slice(0, 10)) {
            // Limit to 10 events for PDF
            if (yPos > 260) {
                doc.addPage();
                yPos = 20;
            }

            const icon = eventIcons[event.eventType] || "📌";

            doc.setFillColor(243, 244, 246);
            doc.roundedRect(margin, yPos, pageWidth - margin * 2, 12, 2, 2, "F");

            doc.setFontSize(9);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(0, 0, 0);
            doc.text(
                `${icon} ${event.eventType.replace(/_/g, " ").toUpperCase()}`,
                margin + 3,
                yPos + 7,
            );

            doc.setFont("helvetica", "normal");
            doc.setTextColor(107, 114, 128);
            doc.text(new Date(event.createdAt).toLocaleString(), pageWidth - margin - 5, yPos + 7, {
                align: "right",
            });

            yPos += 15;
        }

        if (events.length > 10) {
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text(`+ ${events.length - 10} more events`, margin, yPos);
            yPos += 10;
        }
    }

    // ============================================
    // Hash Chain Verification
    // ============================================
    if (proof.hashChainRoot) {
        if (yPos > 240) {
            doc.addPage();
            yPos = 20;
        }

        yPos += 5;

        doc.setFillColor(236, 253, 245);
        doc.roundedRect(margin, yPos, pageWidth - margin * 2, 25, 3, 3, "F");

        doc.setTextColor(22, 163, 74);
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("🔒 Hash Chain Verified", margin + 5, yPos + 8);

        doc.setFontSize(7);
        doc.setFont("courier", "normal");
        doc.setTextColor(75, 85, 99);
        doc.text(proof.hashChainRoot, margin + 5, yPos + 16);

        yPos += 35;
    }

    // ============================================
    // Footer
    // ============================================
    const footerY = doc.internal.pageSize.getHeight() - 15;
    doc.setFillColor(248, 250, 252);
    doc.rect(0, footerY - 5, pageWidth, 20, "F");

    doc.setTextColor(156, 163, 175);
    doc.setFontSize(8);
    doc.text("Tamper-evident proof generated by ShipDocket", pageWidth / 2, footerY + 3, {
        align: "center",
    });
    doc.text(`Document ID: ${proof.id}`, pageWidth / 2, footerY + 8, { align: "center" });

    // Return as Buffer
    const pdfOutput = doc.output("arraybuffer");
    return Buffer.from(pdfOutput);
}
